// <auto-generated />
using System;
using ClientesPro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientesPro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("ClientesPro.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Av. Morelos #123",
                            NombreCompleto = "Ana Gómez Hernández"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Calle Hidalgo #456",
                            NombreCompleto = "Luis Pérez Ortiz"
                        },
                        new
                        {
                            Id = 3,
                            Direccion = "Col. Centro #789",
                            NombreCompleto = "María López Sánchez"
                        },
                        new
                        {
                            Id = 4,
                            Direccion = "Av. Reforma #234",
                            NombreCompleto = "Carlos Ramírez Morales"
                        },
                        new
                        {
                            Id = 5,
                            Direccion = "Calle Juárez #567",
                            NombreCompleto = "Sofía Torres Díaz"
                        });
                });

            modelBuilder.Entity("ClientesPro.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Compras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 2,
                            ClienteId = 1,
                            Estado = "pagado",
                            Fecha = new DateTime(2025, 10, 27, 19, 33, 43, 245, DateTimeKind.Utc).AddTicks(5282),
                            ProductoId = 3,
                            Total = 44.00m
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            ClienteId = 2,
                            Estado = "pendiente",
                            Fecha = new DateTime(2025, 10, 27, 19, 33, 43, 245, DateTimeKind.Utc).AddTicks(5285),
                            ProductoId = 1,
                            Total = 45.00m
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 3,
                            ClienteId = 3,
                            Estado = "pagado",
                            Fecha = new DateTime(2025, 10, 27, 19, 33, 43, 245, DateTimeKind.Utc).AddTicks(5286),
                            ProductoId = 5,
                            Total = 156.00m
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 2,
                            ClienteId = 4,
                            Estado = "cancelado",
                            Fecha = new DateTime(2025, 10, 27, 19, 33, 43, 245, DateTimeKind.Utc).AddTicks(5288),
                            ProductoId = 4,
                            Total = 76.00m
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 5,
                            ClienteId = 5,
                            Estado = "pagado",
                            Fecha = new DateTime(2025, 10, 27, 19, 33, 43, 245, DateTimeKind.Utc).AddTicks(5289),
                            ProductoId = 2,
                            Total = 142.50m
                        });
                });

            modelBuilder.Entity("ClientesPro.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Manzanas frescas",
                            Nombre = "Manzanas Rojas",
                            Precio = 45.00m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Arroz integral de grano largo, alto en fibra y sin gluten.",
                            Nombre = "Arroz Integral",
                            Precio = 28.50m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Leche entera pasteurizada de vaca, rica en calcio y proteínas.",
                            Nombre = "Leche Entera",
                            Precio = 22.00m
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Pan integral artesanal con semillas y harina de trigo 100%.",
                            Nombre = "Pan Integral",
                            Precio = 38.00m
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Huevos provenientes de gallinas libres de jaula, alimentadas naturalmente.",
                            Nombre = "Huevos Orgánicos",
                            Precio = 52.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
